name: required test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  myjob:
    runs-on: ubuntu-latest

    steps:
    - name: Run an one-line script
      # uses: actions/checkout@v3
      run: exit 1
