name: required test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run an one-line script
        run: exit 0
